spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:100.x.x.x}:${DB_PORT:5432}/${DB_NAME:telemetriadb}
    username: ${DB_USER:admin}
    password: ${DB_PASS:secret}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  grafana:
    dashboard-url: ${GRAFANA_DASHBOARD_URL:http://localhost:3000/d-solo/webhardmon-empresa/webhardmon-empresa}
    empresa-dashboard-url: ${GRAFANA_EMPRESA_DASHBOARD_URL:http://localhost:3000/d-solo/webhardmon-empresa/webhardmon-empresa}
    ordenadores-dashboard-url: ${GRAFANA_ORDENADORES_DASHBOARD_URL:http://localhost:3000/d-solo/webhardmon-ordenadores/webhardmon-ordenadores}

server:
  port: 8080